### ISSUE TITLE
tutorial

### ISSUE THREAD

**Issue by woshiyangsi** [colbyford/parEBEN#1]
I am a newer to learn epistasis,could you please share a tutorial of the parEBEN to me?

thanks.

**Comment by woshiyangsi** [comment]
@colbyford

**Comment by woshiyangsi** [comment]
@colbyford

**Comment by colbyford** [comment]
The easiest way to get started is to read about the oringal EBEN R package here: https://cran.r-project.org/web/packages/EBEN/EBEN.pdf

Then, once you understand how to use EBEN, you can parallelize this functionality using parEBEN:
https://www.pornhub.com/view_video.php?viewkey=ph5e7b580e381af&t=145

**Comment by woshiyangsi** [comment]
Okay,thank you.
